version: '3.7'

services:
  front:
    restart: always
    image: mattlangsenkamp/rocfreestands-front:latest
    ports:
      - "8079:8079"
    depends_on:
      - server
  server:
    restart: always
    image: rocfreestands/server:latest
    ports:
      - "8081:8081"
    environment:
      PSQL_HOST: db
      PSQL_USERNAME: rocfreestands
      PSQL_PASSWORD: password
      RFS_USERNAME: admin
      RFS_PASSWORD: admin
      PICTURE_PATH: /pictures
    volumes:
      - server:/app
    depends_on:
      - db

  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: rocfreestands
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  server:
  db:
