name: CI
on:
  pull_request:
  push:
jobs:
  build-for-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt-hotspot
          java-version: 17
      - name: Setup JS
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Build
        run:
          npm install
          npx tailwindcss -i ./style.css -o ./output.css
          sbt compile