name: CI
on:
  pull_request:
  push:
jobs:
  build-for-docker:
    runs-on: ubuntu-latest
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xmx4096M
      JVM_OPTS: -Xmx4096M

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Setup JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: adopt-hotspot
          java-version: 17
      - name: Setup JS
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Buildi
        run:
          npm install;
          sbt docker;
          docker push rocfreestands-http4s:latest mattlangsenkamp/rocfreestands-http4s:latest