name: CI
on:
  pull_request:
    branches:
      main
    types:
      - closed
jobs:
  build-for-docker:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xmx4096M
      JVM_OPTS: -Xmx4096M

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Setup JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: adopt-hotspot
          java-version: 17
      - name: Setup JS
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Buildi
        run:
          npm install;
          sbt docker;
          npm run build;
          docker buildx build -f front.Dockerfile -t mattlangsenkamp/rocfreestands-front:latest .;
          docker push mattlangsenkamp/rocfreestands-http4s:latest;
          docker push mattlangsenkamp/mattlangsenkamp/rocfreestands-front:latest